version: "3.1"

services:
  constraint-gen:
    image: node:14
    environment:
      YARN_CACHE_FOLDER: /opt/yarn-cache
    volumes:
      - ./constraint-gen:/opt/constraint-gen
      - yarn-cache-constraint-gen:/opt/yarn-cache
    working_dir: /opt/constraint-gen
    entrypoint: ./entrypoint.sh
    command: yarn run build

  back:
    image: node:14
    environment:
      YARN_CACHE_FOLDER: /opt/yarn-cache
    volumes:
      - yarn-cache-back:/opt/yarn-cache
      - ./back:/opt/back
      - ./shared:/opt/shared
      - ./scripts:/opt/scripts:ro
      - ./constraint-gen/dist:/opt/constraint-gen:ro
    working_dir: /opt/back
    entrypoint: ./entrypoint.sh
    command: yarn run dev
    depends_on:
      - db
      - constraint-gen

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  front:
    image: node:14
    environment:
      YARN_CACHE_FOLDER: /opt/yarn-cache
    volumes:
      - yarn-cache-front:/opt/yarn-cache
      - ./front:/opt/front
      - ./shared:/opt/shared:ro
      - ./scripts:/opt/scripts:ro
    working_dir: /opt/front
    entrypoint: ./entrypoint.sh
    command: yarn dev
    depends_on:
      - back

  nginx:
    build: nginx-dev
    volumes:
      - ./scripts:/opt/scripts:ro
    depends_on:
      - front
      - back
    ports:
      - 443:443
      - 80:80
    stop_signal: SIGINT

volumes:
  yarn-cache-constraint-gen: null
  yarn-cache-back: null
  yarn-cache-front: null
